---
# Install tasks common to all distros

- block:
    - name: Get vagrant latest pacakges urls
      uri:
        url: "{{ vagrant_engine_download_url }}"
        return_content: yes
        validate_certs: "{{ vagrant_engine_download_validate_certs }}"
      register: get_latest_package_result

    - name: Get installed vagrant version
      command: vagrant -v
      failed_when: no
      changed_when: no
      register: vagrant_engine_version_result
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
