---
# Install tasks for debian
- name: Install required sfotware
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: gnupg2
    state: present

- name: Import apt key certificate
  apt_key:
    url: "{{ vagrant_engine_hashicorp_gpg[ansible_facts.os_family | lower] }}"
    state: present
    validate_certs: no

- name: Configure repository
  apt_repository:
    repo: >-
      deb [arch=amd64] https://apt.releases.hashicorp.com
      {{ ansible_facts.distribution_release }} main
    state: present
    filename: hashicorp

- name: Clean vagrant user dir
  file:
    path: "{{ '/home/'' + user + /.vagrant.d"
    state: absent
  when: vagrant_engine_clean_dir
  loop: "{{ vagrant_engine_users }}"
  loop_control:
    loop_var: user

- name: Install vagrant packages
  apt:
    name: "vagrant={{ version_to_install }}"
    state: present
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
