---
# Install tasks for debian

# Ansible package module does not suppport http(s) remote packages. So we use
# apt module

- name: install vagrant packages
  apt:
    deb: "{{ packages }}"
    state: present
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
