---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/install/common.yml"

    - include_tasks: "{{ install_playbook }}"
      when: >-
        current_version | length == 0
        or current_version is version(version_to_install, "!=")
      vars:
        install_playbook: >-
          {{ role_path
             + "/tasks/install/"
             + ansible_facts.os_family | lower
             + ".yml" }}
        current_version: >-
          {{ vagrant_engine_version_result.stdout
             | default("")
             | regex_replace(".agrant (.*)", "\1") }}
        last_version: >-
          {{ ((get_latest_package_result.content.splitlines()
             | select("search", "vagrant_")
             | list
             | first).split("_")[1]).split("<")[0] }}
        version_to_install: >-
          {{ (vagrant_engine_version is defined )
             | ternary(vagrant_engine_version, last_version) }}
        package_to_install: >-
          {{ "vagrant-" + version_to_install }}

  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
