---
# Install tasks for Red Hat

- name: install vagrant packages
  package:
    name: "{{ package }}"
    state: present
  when: >-
    current_version | length == 0
    or current_version | version_compare(last_version, ">=")
  with_items: "{{ packages }}"
  loop_control:
    loop_var: package
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
