---
# Install tasks for Red Hat

- name: Install vagrant packages
  package:
    name: "{{ packages }}"
    state: present
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
