---
# Install tasks for Red Hat

- name: install vagrant packages
  package:
    name: "{{ package }}"
    state: present
  with_items: "{{ packages }}"
  loop_control:
    loop_var: package
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
