---
# Configuration tasks

- block:
    - name: setup groups
      group:
        name: "{{ item }}"
        state: present
        system: yes
      with_items:
        - vagrant
        - libvirt

    - name: add users to groups
      user:
        append: yes
        groups: '{{ item[0] }}'
        state: present
        name: '{{ item[1] }}'
      with_nested:
        - [ vagrant, libvirt ]
        - "{{ vagrant_engine_users }}"

    # Allow users in vagrant group to manage libvirt without authentication.
    # Details in https://access.redhat.com/documentation/en-us/
    #   red_hat_container_development_kit/2.0/html-single/installation_guide/
    #   #idm139695093806512

    - name: allow vagrant group users to start and stop vagrant boxes
      template:
        src: 10-vagrant-libvirt.rules.j2
        dest: /etc/polkit-1/rules.d/10-vagrant-libvirt.rules
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - restart libvirtd
        - restart polkit
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
