---
# Configuration tasks

- block:
    - name: setup vagrant group
      group:
        name: vagrant
        state: present
        system: yes

    - name: add users to vagrant group
      user:
        append: yes
        groups: vagrant
        state: present
        name: '{{ item }}'
      with_items: "{{ vagrant_engine_users }}"
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
