---
# Install tasks

- block:
    - name: Get vagrant latest pacakges urls
      uri:
        url: "{{ vagrant_engine_download_url }}"
        return_content: yes
        validate_certs: "{{ vagrant_engine_download_validate_certs }}"
      register: get_latest_package_result

    - name: Get installed vagrant version
      command: vagrant -v
      failed_when: no
      changed_when: no
      register: vagrant_engine_version_result

    - name: Import GPG key
      rpm_key:
        state: present
        key: >-
          {{ vagrant_engine_hashicorp_gpg_map
             [ansible_facts.os_family | lower] }}

    - name: Configure repository
      get_url:
        url: "{{ vagrant_engine_yum_repo_url }}"
        dest: "{{ vagrant_engine_yum_repo_file }}"

    - name: Clean vagrant user dir
      file:
        path: "{{ '/home/' + vagrant_engine_user + '/.vagrant.d' }}"
        state: absent
      when: vagrant_engine_clean_user_dir
      loop: "{{ vagrant_engine_users }}"
      loop_control:
        loop_var: vagrant_engine_user

    - name: Install vagrant package
      yum:
        name: "{{ vagrant_engine_package_to_install }}"
        state: present
        allow_downgrade: "{{ vagrant_engine_allow_downgade }}"

  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
