---
# Install tasks

- block:
    - name: install vagrant extra required packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ vagrant_engine_extra_packages }}"

    - name: get vagrant lastest pacakges urls
      uri:
        url: "{{ vagrant_engine_download_url }}"
        return_content: yes
        validate_certs: "{{ vagrant_engine_download_validate_certs }}"
      register: get_latest_package_result

    - name: install vagrant packages
      package:
        name: "{{ item }}"
        state: present
      when: >-
        current_version | length == 0
        or current_version | version_compare(last_version, ">=")
      with_items: "{{ packages }}"
      vars:
        arch_suffix: >-
          {{ (ansible_architecture == "x86_64") | ternary("x86_64", "i686") }}
        packages: >-
          {{ get_latest_package_result.content.splitlines()
             | select("search", arch_suffix + "\.rpm")
             | map("regex_replace", ".*(https:.*\.rpm).*", "\1")
             | list }}
        current_version: >-
          {{ lookup("pipe", "vagrant -v 2>/dev/null || true ") }}
        last_version: >-
          {{ packages
             | first
             | regex_replace(".*/vagrant/(.*)/vagrant.*","\1") }}

    - name: install vagrant plugins
      shell: "vagrant install {{ item }}"
      when: >-
        lookup("pipe",
               "vagrant plugin list | grep " + item + " || true")
        | length == 0
      with_items: "{{ vagrant_engine_plugins }}"

  tags:
      - role::vagrant_engine
      - role::vagrant_engine::packages
      - role::vagrant_engine::install
