---
# Install tasks

- name: install vagrant packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vagrant_engine_packages | default([]) }}"
  become: true
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::packages
    - role::vagrant_engine::install
