---
# Role tasks

- block:
    - name: Install vagrant engine
      include_tasks: install.yml
      tags:
        - role::vagrant_engine::install

    - name: Configure vagrant engine
      include_tasks: configure.yml
      tags:
        - role::vagrant_engine::configure
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::vagrant_engine
