---
# Role tasks

- name: install vagrant engine
  include_tasks: install/main.yml
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::install

- name: configure vagrant engine
  include_tasks: configure/main.yml
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
