---
# Role handlers

- name: vagrant_engine restart libvirtd
  service:
    name: libvirtd
    state: restarted
  listen:
    - restart libvirtd
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::service

- name: vagrant_engine restart polkit
  service:
    name: polkit
    state: restarted
  listen:
    - restart polkit
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::service
