---
# Role handlers

- name: vagrant_engine restart libvirtd
  service:
    name: "{{ service_name }}"
    state: restarted
  listen:
    - restart libvirtd
  vars:
    service_name: >-
      {{ (ansible_distribution | lower in ["rhel", "centos"]
          and ansible_distribution_major_version == "6")
         | ternary("libvirt-guests", "libvirtd") }}
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::service

- name: vagrant_engine restart polkit
  service:
    name: polkit
    state: restarted
  listen:
    - restart polkit
  when: >-
    not (ansible_distribution | lower in ["rhel", "centos"]
         and ansible_distribution_major_version == "6")
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::service
