---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Get vagrant global status
      command: vagrant global-status
      register: vagrant_status_result
      changed_when: no

    - name: Verify vagrant global status
      assert:
        that: >-
          {{ vagrant_status_result.stdout
             is search("id.*name.*provider.*state") }}
