---
# Configuration tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/configure/common.yml"

    - include_tasks: "{{ configure_playbook }}"
      vars:
        configure_playbook: >-
          {{ role_path }}/tasks/configure/{{ ansible_os_family | lower }}.yml
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
