---
# Configuration tasks for all operating systems

- block:

  - name: ensure "vagrant" group is present
    group:
      name: vagrant
      state: present
      system: yes

  - name: "add users to groups"
    user:
      append: yes
      groups: '{{ item[0] }}'
      state: present
      name: '{{ item[1] }}'
    with_nested:
    - - vagrant
      - libvirt
    - "{{ vagrant_engine_users }}"

  - name: "Allow vagrant group users to start and stop Vagrant boxes"
    # https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/2.0/html-single/installation_guide/#idm139695093806512
    template:
      src: 10-vagrant-libvirt.rules.j2
      dest: "/etc/polkit-1/rules.d/10-vagrant-libvirt.rules"
      owner: root
      group: root
      mode: 0644
      backup: yes
    notify:
    - restart libvirtd and polkit services

  become: True
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
