---
# Configuration tasks for Red Hat
- name: Configure machine to use libvirt provider
  when: vagrant_engine_configure_libvirt
  block:
    - name: Check vagrant-libvirt plugin state
      command: vagrant plugin list
      changed_when: no
      register: vagrant_engine_libvirt_plugin_result

    - name: Setup vagrant to use libvirt provider
      when: >-
        vagrant_engine_libvirt_plugin_result.stdout
        is not search("vagrant-libvirt")
      block:
        - name: Setup libvirt group
          group:
            name: libvirt
            state: present
            system: yes

        - name: Add users to libvirt group
          user:
            append: yes
            groups: libvirt
            state: present
            name: '{{ item }}'
          loop: "{{ vagrant_engine_users }}"

        - name: Install software dependencies
          yum:
            name: "{{ package }}"
            state: present
          loop: "{{ vagrant_engine_libvirt_dependencies }}"
          loop_control:
            loop_var: package

        - name: Compile and install vagrant-libvirt plugin
          shell: >-
            CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt
            with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt

        - name: Enabled libvirtd
          service:
            name: libvirtd
            state: started
            enabled: yes
  tags:
    - role::vagrant_engine
    - role::vagrant_engine::configure
    - role::vagrant_engine::configure::libvirt
