---

# Setup vagrant engine in localhost

- name: Setup vagrant engine
  hosts: localhost
  vars_prompt:
    - name: ansible_become_user
      propmpt: User with privileges to install packages
      default: root
      private: no

    - name: ansible_become_pass
      prompt: Password of the user with privileges to install packages
      private: yes

    - name: ansible_become_method
      prompt: Method to become the user with privileges to install packages
      default: su
      private: no

    - name: users
      prompt: >-
        Comma separated list of usernames that should have permissions to run
        vagrant
      default: "root,{{ lookup('env','USER') }}"
      private: no

    - name: delete_vagrant_dir
      prompt: Do you want delete ~/.vagrant.d directory?
      default: no
      private: no

    - name: install_libvirt_plugin
      prompt: Do you to setup libvirt plguin?
      default: no
      private: no

  roles:
    - role: amtega.vagrant_engine
      become: yes
      vars:
        vagrant_engine_users: "{{ users.split(',') | map('trim') | list }}"
        vagrant_engine_clean_user_dir: "{{ delete_vagrant_dir }}"
        vagrant_engine_configure_libvirt: "{{ install_libvirt_plugin }}"
