---

# Setup vagrant engine in localhost

- name: Setup vagrant engine
  hosts: localhost
  vars_prompt:
    - name: ansible_become_user
      propmpt: User with privileges to install packages
      default: root
      private: no

    - name: ansible_become_pass
      prompt: Password of the user with privileges to install packages
      private: yes

    - name: ansible_become_method
      prompt: Method to become the user with privileges to install packages
      default: su
      private: no

    - name: users
      prompt: >-
        Comma separated list of usernames that should have permissions to run
        vagrant
      default: "root,{{ lookup('env','USER') }}"
      private: no

  roles:
    - role: amtega.vagrant_engine
      vagrant_engine_users: "{{ users.split(',') | map('trim') | list }}"
      become: true
