---

# Setup docker engine in localhost

- name: setup vagrant engine
  hosts: localhost
  vars_prompt:
    - name: "users"
      prompt: >-
        Comma separated list of usernames that should have permissions to run
        vagrant"
      default: "root"
      private: no
  roles:
    - role: amtega.vagrant_engine
      vars:
        vagrant_engine_users: "{{ users.split(',') | map('trim') | list }}"
